### ISSUE TITLE
translation url does not work (may be in subfolder)

### ISSUE THREAD

**Issue by khanhtd1108** [VaLeXaR/wp-multilang#10]
Hi @VaLeXaR ,
I tested with new version and seems like it doesn't work correctly with subfolder
Ex: http://demo.phoenixdigi.vn/kosca/
You can switch to Korean but can't back to English (default) by click to en flag?
Can you fix this soon?
Thanks!

**Comment by VaLeXaR** [comment]
Hi @khanhtd1108 
I known about this bug. This will be fixed in new version.
Thank You.

**Comment by VaLeXaR** [comment]
Fixed.
