### ISSUE TITLE
flag image path

### ISSUE THREAD

**Issue by Max-Stirner** [VaLeXaR/wp-multilang#132]
Hello, please sorry about my bad englsh.
There is a way to set a different flag image path? I use amazon clodfront on my wordpress site and all my images are on the cloud, except for the WP-multilang images. If I check with GTMetrix I got this:

https://mydomain.com/wp-content/plugins/wp-multilang/flags/en.png (Dimensions: 18 x 12)
https://mydomain.com/wp-content/plugins/wp-multilang/flags/it.png (Dimensions: 18 x 12)

I would like to set something like https://hhhhhhhhhhhhh4.cloudfront.net/wp-content/plugins/wp-multilang/flags/it.png

It's something I can do?

Thanks and sorry again about my bad english.

**Comment by VaLeXaR** [comment]
Hi. You can use filter 'wpm_flags_dir' for change base dir for flags url.

**Comment by Max-Stirner** [comment]
Hi, thank you!
