### ISSUE TITLE
my woocommerce permalinks are getting translated. how can i stop that? 

### ISSUE THREAD

**Issue by mamnasimjamaly** [VaLeXaR/wp-multilang#14]
[http://mothers-choice.delta-cloud.com.php7-29.phx1-1.websitetestlink.com/fr/produit/pnw00115-penguin-deluxe-single-well-nutritional-warmer/](url)

**Comment by VaLeXaR** [comment]
By url is determined by the current language of the site.
If links not be translated, your site will be on only one language.

**Comment by soft79** [comment]
I think mamnasimjamaly is talking about the /product/ part. 

Setting product permalinks to 'Custom base' `/product/` fixes the issue.

**Comment by VaLeXaR** [comment]
@soft79 maybe.
Some localizations translating permalinks in WC. I don't known why it made.
