### ISSUE TITLE
проблема с переводом виджета

### ISSUE THREAD

**Issue by eXcess-Ika** [VaLeXaR/wp-multilang#2]
здравствуй. 
я никак не могу решить проблему на page builder. вставляю новый виджет, отмечай птишку на каком языке должен паказаца, но все равно отображается на всех языках.

можешь подсказать как решить эту проблему? а так очень удобный плагин.

спасибо заранее.

**Comment by VaLeXaR** [comment]
Hi.
You need view page only on selected languages?

**Comment by eXcess-Ika** [comment]
yes
