### ISSUE TITLE
Latest wordpress 4.9.1 issue

### ISSUE THREAD

**Issue by DangerD256** [VaLeXaR/wp-multilang#22]
Same as in qTranslateX:

```
$post = get_post(233897);
echo '<h2>'.$post->post_title.'</h2>';
echo '<div>'.$post->post_content.'</div>';
```
Returns [:EN]english[:RU]russian[:UA]ukrainian[:]
I can basically wrap all to wpm_translate_value, but is there ability to avoid that to make it parse that automatically?

**Comment by VaLeXaR** [comment]
Hi @DangerD256 
WordPress do not have filters for get_post() in raw mode. Raw mode is using by default. That is why values do not translating. You can use
`get_post(233897, OBJECT, 'display')`

**Comment by DangerD256** [comment]
Thanks, do you have also hook for $wpdb->get_results?

**Comment by VaLeXaR** [comment]
No. DB results view as is.

**Comment by siriokun** [comment]
After installing the latest version with WordPress 4.9.1, I have this warning message:

> Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /home/keloladm/public_html/wp-includes/class-wp-hook.php on line 286

**Comment by VaLeXaR** [comment]
@siriokun Unfortunately I can not. This error occurs when the filter is called. The error message does not provide full information.
