### ISSUE TITLE
Some words that are not translated from the storefront theme with Woocommerce

### ISSUE THREAD

**Issue by watchpci** [VaLeXaR/wp-multilang#23]
everything works except for the specified homepage,

https://www.watchpci.com is by default in French, when I choose another language everything I said is working properly, but currently there is some of the text of the page that I can not find the home page to translate, I think it's own to storefront, if I'm not mistaken

for example in source code generated when reading the page on langage NL (instead french):

Words : Catégories de produit, Acheter par catégorie, nouveautés

how to modify or declare the words in the right languages

sample 1
-------------------------------------------------------------------------------------------------------------------

</div>
<section class="storefront-product-section storefront-product-categories" aria-label="Catégories de produit"><h2 class="section-title">Acheter par catégorie</h2><div class="woocommerce columns-3"><ul class="products">
<li class="product-category product first">

all sources generated
-------------------------------------------------------------------------------------------------------------------

[:fr]Hoodie with Logo[:]

<div id="content" class="site-content" tabindex="-1">
		<div class="col-full">

		<div class="woocommerce"></div>
	<div id="primary" class="content-area">
		<main id="main" class="site-main" role="main">

			
<div id="post-76" class="post-76 page type-page status-publish hentry" style="" data-featured-image="">
	<div class="col-full">
		<a class="button storefront-hero__button-edit" href="https://watchpci.com/wp-admin/post.php?post=76&amp;action=edit">Modifier cette section</a>		<header class="entry-header">
			<h1 class="entry-title">Welkom</h1>		</header>
				<div class="entry-content">
			<div class="component">
<div class="self mobile-leaf text textnormal">
<p>Eenmaal gereduceerd tot de functie van de tijdindicatie, het horloge is aanzienlijk gegroeid tot het punt van steeds vandaag een onmisbaar mode-accessoire! Van de grote uurwerken huizen aan de meest modieuze makers, ze allemaal in de kijker. Klassiek of excentriek, gekleurd of Verenigd, leder of staal, automatische of Quartz… Om te kiezen voor een horloge is om zijn persoonlijkheid te uiten, zijn stemming van het moment, maar ook om zijn stijl te bevestigen. Je kan net zo goed zeggen dat het moeilijk is om slechts een! Voor u, WatchPCI zal u toelaten om uw horloge online te kopen in vrede.</p>
</div>
</div>
					</div>
			</div>
</div>
<section class="storefront-product-section storefront-product-categories" aria-label="Catégories de produit"><h2 class="section-title">Acheter par catégorie</h2><div class="woocommerce columns-3"><ul class="products">
<li class="product-category product first">
	<a href="https://www.watchpci.com/nl/boutique/accessories/"><img src="https://watchpci.com/wp-content/uploads/2017/12/61o03eH-7pL._SL1500_-300x300.jpg" alt="Accessoires" width="300" height="300" srcset="https://watchpci.com/wp-content/uploads/2017/12/61o03eH-7pL._SL1500_-300x300.jpg 300w, https://watchpci.com/wp-content/uploads/2017/12/61o03eH-7pL._SL1500_-150x150.jpg 150w, https://watchpci.com/wp-content/uploads/2017/12/61o03eH-7pL._SL1500_-768x768.jpg 768w, https://watchpci.com/wp-content/uploads/2017/12/61o03eH-7pL._SL1500_-1024x1024.jpg 1024w, https://watchpci.com/wp-content/uploads/2017/12/61o03eH-7pL._SL1500_-180x180.jpg 180w, https://watchpci.com/wp-content/uploads/2017/12/61o03eH-7pL._SL1500_-600x600.jpg 600w, https://watchpci.com/wp-content/uploads/2017/12/61o03eH-7pL._SL1500_.jpg 1500w" sizes="(max-width: 300px) 100vw, 300px">		<h2 class="woocommerce-loop-category__title">
			Accessoires <mark class="count">(1)</mark>		</h2>
		</a></li>
<li class="product-category product">
	<a href="https://www.watchpci.com/nl/boutique/montre-femme/"><img src="https://watchpci.com/wp-content/uploads/2017/12/valerie_1024x1024-300x300.jpg" alt="Dameshorloge" width="300" height="300" srcset="https://watchpci.com/wp-content/uploads/2017/12/valerie_1024x1024-300x300.jpg 300w, https://watchpci.com/wp-content/uploads/2017/12/valerie_1024x1024-150x150.jpg 150w, https://watchpci.com/wp-content/uploads/2017/12/valerie_1024x1024-768x768.jpg 768w, https://watchpci.com/wp-content/uploads/2017/12/valerie_1024x1024-180x180.jpg 180w, https://watchpci.com/wp-content/uploads/2017/12/valerie_1024x1024-600x600.jpg 600w, https://watchpci.com/wp-content/uploads/2017/12/valerie_1024x1024.jpg 1024w" sizes="(max-width: 300px) 100vw, 300px">		<h2 class="woocommerce-loop-category__title">
			Dameshorloge <mark class="count">(56)</mark>		</h2>
		</a></li>
<li class="product-category product last">
	<a href="https://www.watchpci.com/nl/boutique/montre-homme/"><img src="https://watchpci.com/wp-content/uploads/EA/AR5905/IMG_0033_2048x2048_6c663725-f61d-4662-a051-7793c7c8c813_grande-300x300.jpg" alt="Herenhorloge" width="300" height="300" srcset="https://watchpci.com/wp-content/uploads/EA/AR5905/IMG_0033_2048x2048_6c663725-f61d-4662-a051-7793c7c8c813_grande-300x300.jpg 300w, https://watchpci.com/wp-content/uploads/EA/AR5905/IMG_0033_2048x2048_6c663725-f61d-4662-a051-7793c7c8c813_grande-150x150.jpg 150w, https://watchpci.com/wp-content/uploads/EA/AR5905/IMG_0033_2048x2048_6c663725-f61d-4662-a051-7793c7c8c813_grande-180x180.jpg 180w" sizes="(max-width: 300px) 100vw, 300px">		<h2 class="woocommerce-loop-category__title">
			Herenhorloge <mark class="count">(80)</mark>		</h2>
		</a></li>
</ul>
</div></section><section class="storefront-product-section storefront-recent-products" aria-label="Produits récents"><h2 class="section-title">Nouveautés</h2><div class="woocommerce columns-4 "><ul class="products">
<li class="post-2008 product type-product status-publish has-post-thumbnail product_brands-mk product_cat-montre-femme product_cat-mks product_tag-mks product_shipping_class-livstd first instock sale sold-individually taxable shipping-taxable purchasable product-type-simple">
	
<div data-item_id="2008" data-action="alg-wc-wl-toggle" class="alg-wc-wl-btn add alg-wc-wl-thumb-btn alg-wc-wl-thumb-btn-abs alg-wc-wl-thumb-btn-loop" style="left: 17px; top: 17px; right: auto; bottom: auto; display: block;">
	<div class="alg-wc-wl-view-state alg-wc-wl-view-state-add">
		<i class="fa fa-heart" aria-hidden="true"></i>
	</div>
	<div class="alg-wc-wl-view-state alg-wc-wl-view-state-remove">
		<i class="fa fa-heart" aria-hidden="true"></i>
	</div>
	        <i class="loading fa fa-refresh fa-spin fa-fw"></i>
	</div><a href="https://www.watchpci.com/nl/product/mk6141/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="300" height="300" src="//watchpci.com/wp-content/uploads/2017/12/171023092302_11-300x300.jpg" class="attachment-shop_catalog size-shop_catalog wp-post-image" alt="" srcset="//watchpci.com/wp-content/uploads/2017/12/171023092302_11-300x300.jpg 300w, //watchpci.com/wp-content/uploads/2017/12/171023092302_11-150x150.jpg 150w, //watchpci.com/wp-content/uploads/2017/12/171023092302_11-180x180.jpg 180w, //watchpci.com/wp-content/uploads/2017/12/171023092302_11-600x600.jpg 600w, //watchpci.com/wp-content/uploads/2017/12/171023092302_11.jpg 720w" sizes="(max-width: 300px) 100vw, 300px"><h2 class="woocommerce-loop-product__title">MICHAEL KORS MK6141 PARKER 39MM LADIES'</h2>
	<span class="onsale">Aanbieding!</span>

Many thaznks for your helps

**Comment by VaLeXaR** [comment]
Some string are in the localization for current language. And You need edit localization for current language or create new if it not exist. Find localization in your theme.

**Comment by watchpci** [comment]
Hello my friends, 

many thanks for your feedback, but it's already indicated

see ...
/**
 * WordPress Localized Language, defaults to English.
 *
 * Change this to localize WordPress. A corresponding MO file for the chosen
 * language must be installed to wp-content/languages. For example, install
 * de_DE.mo to wp-content/languages and set WPLANG to 'de_DE' to enable German
 * language support.
 */
define('WPLANG', 'fr_FR');

the problem is that it works 90% of the whole site, as soon as it works and that I adapt the files of translations either all is in the same language in French instead of English which was of origin, like my homepage, why are some words not translated

I admit that I am not an expert in development, and it has been a few years since I had touched the realization of website

Thank you for you precious help
Vincent



Le 25 décembre 2017 à 02:24, Valentyn Riaboshtan <notifications@github.com> a écrit :

Some string are in the localization for current language. And You need edit localization for current language or create new if it not exist. Find localization in your theme.

**Comment by VaLeXaR** [comment]
Hi @watchpci 
The constant WPLANG is deprecated. Not using this.
The localization of WooCommerce is not finished https://goo.gl/ZbGmL1 As you see many strings is not translated.
I'm sure that your theme too has many not translated strings. And You need as semselves edit localization files. You cat do it with WP plugin Loco Translate or the program POEdit.

**Comment by watchpci** [comment]
re many thanks, 

I use LOCO and POEDIT, that's what I'm busy doing with POEDIT, because LOCO is too long to do.
I'm just afraid I do not have the right POT files for LOCO, or that POEDIT does not modify the necessary file

but you just give me a clue, maybe the woocommerce plugin, but again scared to break everything despite the backup

I'll tell you what if I succeeded or not

Vincent @watchpci

Le 29 décembre 2017 à 10:07, Valentyn Riaboshtan <notifications@github.com> a écrit :

Hi @watchpci
The constant WPLANG is deprecated. Not using this.
The localization of WooCommerce is not finished https://goo.gl/ZbGmL1 As you see many strings is not translated.
I'm sure that your theme too has many not translated strings. And You need as semselves edit localization files. You cat do it with WP plugin Loco Translate or the program POEdit.
