### ISSUE TITLE
Widget Switch

### ISSUE THREAD

**Issue by tjsl** [VaLeXaR/wp-multilang#25]
I want to display the Language selection to Display Horizontally 

The widget only allows drop down or as a list vertically. 

Can you please tell me how do i make it look horizontal like 

English | සිංහල |  தமிழ்

**Comment by VaLeXaR** [comment]
Use css for customize appearance.

**Comment by tjsl** [comment]
Where is the CSS file?The code which I needed to be edit, but I cannot find it in Wordpress.
I found the php file for the language switcher list option and i tried editing it. But I wasn't success to accomplishment of my requirement.

**Comment by VaLeXaR** [comment]
You can add custom css in css file in your theme, or use custom css option in customizer.
