### ISSUE TITLE
Issue with "PODS" plugin

### ISSUE THREAD

**Issue by ommedical** [VaLeXaR/wp-multilang#27]
Dear its very usefull plugin but i found an issue that it doesnt work with "PODS" plugin..
I'd tried it on my local server..
used wp latest 4.9.1 and used pods plugin 2.7.1 also used WP Multilang Version 2.1.11 plugin..
after installation of wp ..
i installed first wp multilang ..
than i installed pods ..
wp multilang works fine with native "pages object" ..
but not working when created "New pods object",,,

**Comment by VaLeXaR** [comment]
Is this plugin in  list of supported  plugins WP Multilang?

**Comment by ommedical** [comment]
i don't know..
but i think pods plugin is very dynamic and essential plugin..
hope you'll try to figure it out and make it able to work with pods..

**Comment by ommedical** [comment]
pods is a kind of advanced custom field plugin but yet much simple and advanced and also free

**Comment by ivanweiler** [comment]
For pods, it is possible to create wpm-config.json file inside active theme with something like this:
```
{  
  "post_types": {  
    "speaker": {}  
  },
  "post_fields": {
    "company": {}
  }
}
```
where speaker is my custom post type (created from pods) and company is speaker field. Translation works then.
 
Hope it helps.

**Comment by ommedical** [comment]
thankx @ivanweiler for your kind sugession..
also would like to tell that im not techee developer..
you discribed the solution very nicely..
but i think the solution is for a specific custome post and it's related fields..
but what about the "dynamic" way..
i think it will be better if developers of this plugin can do the same things for compatibility of PODS plugin..
as PODS plugin is very usefull and advance and yet opensource and free also..

hope you all with developers also consider the usefullness of these both plugins..
and also for all that community that cannot afford paid plugins..

thanx alot again for nice solution and reply..  :-) _/|\_

**Comment by VaLeXaR** [comment]
@ommedical Compatibility with rich plugins takes a lot of time and effort. I'm just developing this plugin in my free time. And from this I do not get any profit. Therefore, the support for additional plugins in the free version is unlikely.
