### ISSUE TITLE
Menu does not allow multilang

### ISSUE THREAD

**Issue by AlvaroGutardj** [VaLeXaR/wp-multilang#28]
Hello!
first of all, thanks for your great plugin!

But, now i have a trouble, if a desinstall it my menu goes crazy.

I do not want to deinstall it, but if i add a item with url, it does not use different url for every language.

Do yo know what is wrong?. Lot´s of thanks!

**Comment by VaLeXaR** [comment]
Hi @AlvaroGutardj 
You mean a different slugs in url or language prefix?

**Comment by AlvaroGutardj** [comment]
Excuse my english my friend!
I am going to try to explain it.

If i put a button with: "FOR SALE CARS" and i want to send it to www.buy4life.es/en/forsalecars the spanish button in menu also send me there. (I only use one tab when i do this... i remember last week it worked fine but i had troubles with https protocol... )

**Comment by VaLeXaR** [comment]
Check the site url in site settings.
I think in your settings the site url without https protocol.

**Comment by AlvaroGutardj** [comment]
I already put it without https, same problem.
If i want use a url in a button in menu, it is the same for each language... 
I do not know how can i fix this...

**Comment by VaLeXaR** [comment]
No, if your site is using https, you need set url in the site address setting with https.
What url You need to translate? Custom link?

**Comment by AlvaroGutardj** [comment]
I do not need to translate, these are the real links:
If you are viewing Spanish menú:
https://buy4life.es/?maker=all&model=&mileage_to=&fuel_type=&type=&location=&gearbox=&status=46&tfseekfid=main_search&s=%7E
But if you are viewing English menu shold be:
https://buy4life.es/en/?maker=all&model=&mileage_to=&fuel_type=&type=&location=&gearbox=&status=46&tfseekfid=main_search&s=%7E

When i put it in custom link, both languages get the last url what i put.

THANKS FOR YOUR TIME

**Comment by VaLeXaR** [comment]
If url is from same domen then just added language tag.
So Yon ned to add in url field https://buy4life.es/?maker=all&model=&mileage_to=&fuel_type=&type=&location=&gearbox=&status=46&tfseekfid=main_search&s=%7E ? without /en/. And on english version the link will be like https://buy4life.es/en/?maker=all&model=&mileage_to=&fuel_type=&type=&location=&gearbox=&status=46&tfseekfid=main_search&s=%7E

**Comment by AlvaroGutardj** [comment]
I understand!

But when i am in english version the button does not add /en/

**Comment by AlvaroGutardj** [comment]
I want to say, it is like the pluggin does not work. If i click in "for sale cars" in english version it redirects me to original version.

**Comment by AlvaroGutardj** [comment]
![imagen](https://user-images.githubusercontent.com/35973019/35612848-7b3fd146-066a-11e8-9d4e-5bae6d154860.png)
Spanish version
![imagen](https://user-images.githubusercontent.com/35973019/35612898-97c9efae-066a-11e8-966c-092745e5ea5b.png)
English Version

![imagen](https://user-images.githubusercontent.com/35973019/35612956-c654487e-066a-11e8-87e1-dc48d639a905.png)
Menu url in english version...

I am very dissapointed... BUT A LOT´S OF THANKS FOR HELPING ME

**Comment by VaLeXaR** [comment]
add link with protocol

**Comment by AlvaroGutardj** [comment]
do you mean https:// ?

**Comment by AlvaroGutardj** [comment]
This way?
![imagen](https://user-images.githubusercontent.com/35973019/35615703-38ffc774-0673-11e8-83ab-833ef8883394.png)

**Comment by AlvaroGutardj** [comment]
OHHH MY GOD.... IT WORKS!!!! 

But i must to add... my firefox browser gives me troubles!!! with chrome it works great


THANKS THANKS THANKS!!!!!

**Comment by VaLeXaR** [comment]
Clear cache on Firefox.

**Comment by AlvaroGutardj** [comment]
Thanks again, solved!
