### ISSUE TITLE
Problem with post title

### ISSUE THREAD

**Issue by richardmaxbr** [VaLeXaR/wp-multilang#29]
Good afternoon, I'm using the plugin and I have the following problem, when I post only in Portuguese, the title appears [pt] if posted in Spanish and English aparere [es] [en] and this only appears in facebook and twitter in the blog appears normal.

For example:
[pt] post test []
[en] post test [] [es] test del post (in Spanish) [] post test (in English)

does it have just POST TEST, without the [] language?

Use to post on facebook and twitter the SNAP plugin AUTOPOSTER

Thank you so much

Site: www.rmax.com.br

**Comment by VaLeXaR** [comment]
Thank You. It will be fixed in next version.

**Comment by VaLeXaR** [comment]
Fixed

**Comment by richardmaxbr** [comment]
Good morning, the problem continues even after the upgrade.

The [en] example [] is still displayed

see on my facebook page how it looks

https://www.facebook.com/Rmaxbr/

Thanks for helping

**Comment by VaLeXaR** [comment]
Hi. What are You using for posting to Facebook?

**Comment by richardmaxbr** [comment]
This plugin https://www.nextscripts.com/

**Comment by VaLeXaR** [comment]
WP Multilang is not responsible for posting to Facebook. Developers at https://www.nextscripts.com/ do not filter the title through standard WP features, but send it in raw form. If this plugin has a title filter, then you need to apply the function 'wpm_translate_string' to the header.

**Comment by richardmaxbr** [comment]
Could you explain how to put it? I'm a little lay on the programming part.

**Comment by VaLeXaR** [comment]
Try to add the code to your functions.php file.
`
function nxs_doQTrans($text) {
	return wpm_translate_string($text);
}
`
