### ISSUE TITLE
Migration from qTranslate-X

### ISSUE THREAD

**Issue by cgidds** [VaLeXaR/wp-multilang#3]
From what I gather, WPMultilang is an "upgrade" from qTranslate-X based on the conversation in this [thread](https://github.com/qTranslate-Team/qtranslate-x/issues/476). Have you come up with a migration process from qTranslate-X to WPMultilang? We have 30,000+ posts, and I am still working out bugs from migrating to qTranslate-X a few months ago from WPML so if WPMultilang is more stable, I'm happy to do another migration. Just need to know what that process is and if it's smooth.

**Comment by VaLeXaR** [comment]
Hi. WP Multilang is not new qTranslate-X. It have another principle of work.
WP Multilang works by filters and actions. It just use syntax of qTranslate-X.
Also can translate strings that in syntax of WPGlobus, qTranslate or mqTranslate.
All WP Multilang settings you have to be done manually. WP Multilang does not support qTranslate-X settings.
First, do it on the test site.

**Comment by cgidds** [comment]
Ok, thanks for the insight. That helps.
