### ISSUE TITLE
How can i get selected language in admin panel?

### ISSUE THREAD

**Issue by DangerD256** [VaLeXaR/wp-multilang#30]
In admin panel language is set to Russian (at top bar), but wpm_get_language() returns "uk" at meta box... (uk even not default language). wpm_set_new_value also uses "uk" as default...
What function i need to use to get current selected language?

**Comment by VaLeXaR** [comment]
Ви маєте на увазі мову, що увімкнена для редагування? Чи та що використовується для локалізації?

**Comment by DangerD256** [comment]
Мову яка увiмкнена.

**Comment by VaLeXaR** [comment]
`$edit_lang = !empty($_GET['edit_lang']) ? $_GET['edit_lang'] : get_user_meta( get_current_user_id(), 'edit_lang', true );`
