### ISSUE TITLE
Language selector in single post/page edit mode disappeared with Gutenberg 2.2

### ISSUE THREAD

**Issue by Theremingenieur** [VaLeXaR/wp-multilang#32]
Since the Gutenberg 2.2 update, the little flag selector in edit mode for single pages or posts in the top left corner has disappeared. Thus, switching from on translation to another for the same page or post requires going back to all posts or all pages, switch the language there, and re-entering edit mode again - a pain in the ass...

**Comment by VaLeXaR** [comment]
Thank You. Will be fixed in next version.
