### ISSUE TITLE
Suugestion: custom post type settings in admin screen

### ISSUE THREAD

**Issue by Theremingenieur** [VaLeXaR/wp-multilang#34]
To improve compatibility with manifold plugins in an easy way:
Add a panel in the admin screen where all registered and activated custom post types are listed with checkboxes to activate multi language individually for these. Willing to pay for that feature because adding manually custom json files is a pain in the a... and often, these are deleted by plugin or theme updates.

**Comment by VaLeXaR** [comment]
It will not help. There are situations where you need to set up the translation of only certain fields in a post. For example, the translation is only 'post_title' but does not translate 'post_content' and 'post_excerpt'. There are also plugins stored in 'post_content' or 'post_excerpt' serialized arrays and you need to make a configuration for translating this array. Therefore, checking checkboxes for selecting a post type for translating is not a way.
