### ISSUE TITLE
Custom post issue after latest update.

### ISSUE THREAD

**Issue by DangerD256** [VaLeXaR/wp-multilang#35]
Обновил вчера плагин до последней версии, отвалились кастомные посты.

wpm-config.json
```
{
  "post_types": {
    "catalog": null,
    },
  },
  "taxonomies": {
    "category" : null,
    "cat_category" : null,
    "manufacturer" : null,
  },
}

```

**Comment by VaLeXaR** [comment]
Your config is incorrect. You had disable custom post types and taxonomies for translating.

**Comment by DangerD256** [comment]
What's wrong here? Previously worked...
```
{
  "post_types": {
    "page": {},
    "slider_popular": {},
    "slider": {},
    "catalog": {},
    "post": {},
    "attachment": {},
    "nav_menu_item": {
      "attr_title": {},
      "title": {}
    },
    "any": {},
    "customize_changeset": null,
    "revision": null
  },
  "post_fields": {
    "_wp_attachment_image_alt": {}
  },
  "taxonomies": {
    "category" : {},
    "cat_category" : {},
    "manufacturer" : {},
    //"slider_popular_cats" : {},
    "post_tag" : {}
  },
  "term_fields": {},
  "user_fields": {},
  "comment_fields": {},
  "admin_pages": [
    "upload",
    "nav-menus",
    "options-general",
    "widgets",
    "settings-network",
    "site-settings-network"
  ],
  "options": {
    "blogname": {},
    "blogdescription": {}
  },
  "site_options": {
    "site_name": {},
    "welcome_email": {},
    "first_post": {},
    "welcome_user_email": {},
    "first_page": {},
    "first_comment": {}
  },
  "widgets": {
    "media_image": {
      "caption": {},
      "alt": {},
      "image_title": {}
    },
    "custom_html": {
      "content": {}
    }
  },
  "admin_html_tags": {}
}

```

**Comment by VaLeXaR** [comment]
If You want to translate post type, You need set empty object(array) in config file. If You need disable translating, You need set `null`.
For translating.
`
  "post_types": {
    "catalog": {}
  },
`

For disable translating.
`
  "post_types": {
    "catalog": null
  },
`
The config file `wpm-config.json` You need to put in a root of your theme.

**Comment by sashalifestar** [comment]
This can be done like this
`add_filter( 'wpm_load_config', [ $this, 'set_config' ] );
...
	/**
	 * @param array $config
	 *
	 * @return array
	 */
	public function set_config( array $config ): array {
		$config['post_types']['news'] = [];
		$config['post_types']['staff'] = [];

		return $config;
	}
`
Where news and staff are custom post types

**Comment by DangerD256** [comment]
I have  "catalog": {}, in config, but currently it doesn't works, I will try to  reinstall everything

**Comment by VaLeXaR** [comment]
@DangerD256 Which is the screen_id for the post type?

**Comment by DangerD256** [comment]
```

WP_Screen Object
--
  | (
  | [action] =>
  | [base] => post
  | [columns:WP_Screen:private] => 2
  | [id] => catalog
...
```
Config file:
http://ritmindustry.com/wp-content/themes/ritm/wpm-config.json

**Comment by VaLeXaR** [comment]
Your JSON file is invalid. JSON syntax does not contain comments.
```
{
  "post_types": {
    "slider_popular": {},
    "slider": {},
    "catalog": {}
  },
  "taxonomies": {
    "manufacturer" : {}
  }
}
```
The right config.

**Comment by DangerD256** [comment]
thanks dude, my fault =)
