### ISSUE TITLE
[question/ feature request] Shortcode to add the switcher widget elsewhere or in a page.

### ISSUE THREAD

**Issue by Pixelatex** [VaLeXaR/wp-multilang#36]
Because of... design reasons... we don't use the standard header, instead, our headers are built into the page with visual composer.

Is there something in place to use a shortcode or something else to implant the switcher in a page or just anywhere?

p.s. loving your plugin, keep up the good work dude!

**Comment by VaLeXaR** [comment]
Hi @Pixelatex 
This is only one function.
```
add_shortcode( 'wpm_lang_switcher', function ( $atts ) {

	$atts = shortcode_atts( array(
		'type' => 'list',
		'show' => 'both'
	), $atts);

	return wpm_get_language_switcher( $atts['type'], $atts['show'] );
} );
```

**Comment by Pixelatex** [comment]
Alright, that will do the trick :) just have to tweak the styling a bit.

Thanks for adding clear class names to all the divs, makes my job much easier :)
