### ISSUE TITLE
Onepress theme translation

### ISSUE THREAD

**Issue by jernejpangersic** [VaLeXaR/wp-multilang#37]
Hi,

I tried the plugin to translate the Onepress theme (https://www.famethemes.com/themes/onepress/).
I managed to do some of the translations, but some don't work.
For example - I can translate all of the section titles, but I can't translate the text in the hero unit. Am I doing something wrong?

So I've put the text like this:
> [:en]Some English text[:sl]Some Slovenian text
But unfortunately the text is not translated. The website displays "[:en]Some English text[:sl]Some Slovenian text" instead of the translation

Thanks in advance!

**Comment by VaLeXaR** [comment]
Hi
What are You using for the slider? If it are options add it to config file.

**Comment by jernejpangersic** [comment]
Hi,
Sorry I'm not sure what you mean?

**Comment by VaLeXaR** [comment]
Where the slider save its data?
