### ISSUE TITLE
Please add endpoints to the REST API

### ISSUE THREAD

**Issue by vrxj81** [VaLeXaR/wp-multilang#4]
Would it be possible to add endpoints to the REST API to access configuration, setup languages and, most important to me, get al available languages?

**Comment by VaLeXaR** [comment]
Hi @vrxj81 
All WP Multilang settings added to REST for WP settings.
In develop branch fixed adding language setting. You can try this.

**Comment by VaLeXaR** [comment]
Hi @vrxj81 
I did add setting to REST in develop branch. Try this.

**Comment by VaLeXaR** [comment]
Endpoin for WPM settings is standart WP settings endpoint.
