### ISSUE TITLE
[Woocommerce] coupon text not being translated.

### ISSUE THREAD

**Issue by Pixelatex** [VaLeXaR/wp-multilang#40]
It seems the add coupon text is not being translated automatically while the rest of the checkout form is.
I tried looking into the config file but I can't figure out what I'm missing to fix this.

Can you help me figure this out?

**Comment by VaLeXaR** [comment]
```
{
  "post_types": {
    "shop_coupon": {
      "post_name": null,
      "post_content": null
    }
  }
}
```

**Comment by Pixelatex** [comment]
I'm noticing some bits and bobs that are also lacking translations, what's the logic behind the names?

**Comment by VaLeXaR** [comment]
I do not understand your question.

**Comment by Pixelatex** [comment]
some labels are not being translated correctly and are possibly also missing in the config. How do I find the correct names like 'shop_coupon' to write in the config?

**Comment by Pixelatex** [comment]
`{
  "post_types": {
    "product": {},
    "product_variation": {},
    "shop_coupon": {
      "post_name": null,
      "post_content": null
    }
  },
  "post_fields": {
    "_button_text": {},
    "_purchase_note": {},
    "_variation_description": {}
  },
  "taxonomies": {
    "product_cat" : {},
    "product_tag" : {},
    "product_shipping_class" : {}
  },
  "admin_pages": [
    "woocommerce_page_wc-settings",
    "product_page_product_attributes"
  ],
  "options": {
    "woocommerce_store_address": {},
    "woocommerce_store_address_2": {},
    "woocommerce_store_city": {},
    "woocommerce_email_footer_text": {},
    "woocommerce_demo_store_notice": {},
    "woocommerce_price_thousand_sep": {},
    "woocommerce_price_decimal_sep": {},
    "woocommerce_price_display_suffix": {},
    "woocommerce_email_from_name": {},
    "woocommerce_new_order_settings": {
      "subject" : {},
      "heading" : {}
    },
    "woocommerce_customer_completed_order_settings": {
      "subject" : {},
      "heading" : {},
      "subject_downloadable" : {},
      "heading_downloadable" : {}
    },
    "woocommerce_customer_invoice_settings": {
      "subject" : {},
      "heading" : {},
      "subject_paid" : {},
      "heading_paid" : {}
    },
    "woocommerce_customer_new_account_settings": {
      "subject" : {},
      "heading" : {}
    },
    "woocommerce_customer_note_settings": {
      "subject" : {},
      "heading" : {}
    },
    "woocommerce_customer_reset_password_settings": {
      "subject" : {},
      "heading" : {}
    },
    "woocommerce_customer_processing_order_settings": {
      "subject" : {},
      "heading" : {}
    },
    "woocommerce_cancelled_order_settings": {
      "subject" : {},
      "heading" : {}
    },
    "woocommerce_failed_order_settings": {
      "subject" : {},
      "heading" : {}
    },
    "woocommerce_customer_on_hold_order_settings": {
      "subject" : {},
      "heading" : {}
    },
    "woocommerce_customer_refunded_order_settings": {
      "subject_full" : {},
      "heading_full" : {},
      "subject_partial" : {},
      "heading_partial" : {}
    },
    "woocommerce_paypal_settings": {
      "title" : {},
      "description" : {},
      "instructions" : {}
    },
    "woocommerce_cheque_settings": {
      "title" : {},
      "description" : {},
      "instructions" : {}
    },
    "woocommerce_bacs_settings": {
      "title" : {},
      "description" : {},
      "instructions" : {}
    },
    "woocommerce_cod_settings": {
      "title" : {},
      "description" : {},
      "instructions" : {}
    },
    "woocommerce_bacs_accounts": {
      "wpm_each": {
        "account_name": {},
        "bank_name": {}
      }
    }
  },
  "admin_html_tags": {
    "product_page_product_attributes": {
      "value": [
        "#attribute_label"
      ]
    }
  }
}`

This is my current config and it is still showing coupon as untranslated, am I missing something? The config file is included in my functions as 

`add_filter ( 'wpm_post_post_config', '__return_null');`

**Comment by VaLeXaR** [comment]
"shop_coupon" it is a post type. So You need add the post type to config.
The post type saving its text in excerpt field. You need to translate the field but do not need to translate others fields (like title, content ).

**Comment by VaLeXaR** [comment]
You need to add your config in the file "wpm-config.json".

**Comment by Pixelatex** [comment]
that file I posted is the wpm-config.json that's located in the root of my child theme but it doesn't really seem to do anything

**Comment by VaLeXaR** [comment]
You do not need to add all from woocommerce.json to your wpm-config.json. You need to add only needed configuration. Like:
```
{
  "post_types": {
    "shop_coupon": {
      "post_name": null,
      "post_content": null
    }
  }
}
```

**Comment by Pixelatex** [comment]
Yeah, but even with just that. It's not working, your readme says to update a plugin for the config to work, does this mean the woocommerce plugin specifically? or any plugin?

**Comment by soft79** [comment]
I suspect it's not related to wp-multilang.

"Add coupon" is part of the WC template. Is translation possibly missing in the .po/.mo? Or does theme override this text maybe?

Please paste WC System Status Report.

**Comment by Pixelatex** [comment]
@soft79 

`
### WordPress Environment ###

Home URL: --
Site URL: --
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.34
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.52.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 10.39MB
Database Data Size: 8.97MB
Database Index Size: 1.42MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
ofzh_commentmeta: Data: 0.02MB + Index: 0.03MB
ofzh_comments: Data: 0.02MB + Index: 0.08MB
ofzh_links: Data: 0.02MB + Index: 0.02MB
ofzh_options: Data: 1.52MB + Index: 0.02MB
ofzh_postmeta: Data: 0.08MB + Index: 0.03MB
ofzh_posts: Data: 0.05MB + Index: 0.06MB
ofzh_termmeta: Data: 0.02MB + Index: 0.03MB
ofzh_terms: Data: 0.02MB + Index: 0.03MB
ofzh_term_relationships: Data: 0.02MB + Index: 0.02MB
ofzh_term_taxonomy: Data: 0.02MB + Index: 0.03MB
ofzh_usermeta: Data: 0.02MB + Index: 0.03MB
ofzh_users: Data: 0.02MB + Index: 0.05MB
wp_bwg_album: Data: 0.02MB + Index: 0.00MB
wp_bwg_album_gallery: Data: 0.02MB + Index: 0.00MB
wp_bwg_gallery: Data: 0.02MB + Index: 0.00MB
wp_bwg_image: Data: 0.02MB + Index: 0.00MB
wp_bwg_image_comment: Data: 0.02MB + Index: 0.00MB
wp_bwg_image_rate: Data: 0.02MB + Index: 0.00MB
wp_bwg_image_tag: Data: 0.02MB + Index: 0.00MB
wp_bwg_shortcode: Data: 0.02MB + Index: 0.00MB
wp_bwg_theme: Data: 0.08MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_event_hours: Data: 0.00MB + Index: 0.00MB
wp_layerslider: Data: 0.02MB + Index: 0.00MB
wp_layerslider_revisions: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB
wp_nextend2_section_storage: Data: 0.02MB + Index: 0.03MB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB
wp_nextend2_smartslider3_sliders: Data: 0.03MB + Index: 0.00MB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.00MB
wp_nextend2_smartslider3_slides: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.09MB + Index: 0.05MB
wp_postmeta: Data: 0.30MB + Index: 0.09MB
wp_posts: Data: 3.47MB + Index: 0.06MB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_revslider_slides: Data: 0.02MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_strong_views: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wd_fb_data: Data: 0.02MB + Index: 0.00MB
wp_wd_fb_info: Data: 0.02MB + Index: 0.00MB
wp_wd_fb_option: Data: 0.02MB + Index: 0.00MB
wp_wd_fb_shortcode: Data: 0.02MB + Index: 0.00MB
wp_wd_fb_theme: Data: 0.02MB + Index: 0.00MB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 65
bwg_gallery: 1
carousels: 2
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 7
page: 13
polylang_mo: 3
post: 2
product: 1
product_variation: 4
revision: 129
shop_order: 2
slides: 1
testimonials: 8
wpcf7_contact_form: 2
wpm-testimonial: 3
wpsl_stores: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (23) ###

LayerSlider WP: by Kreatura Media – 6.3.0
Contact Form 7: by Takayuki Miyoshi – 5.0.1
Custom Facebook Feed: by Smash Balloon – 2.5
Duplicate Post: by Enrico Battocchi – 3.2.1
Envato Market: by Envato – 2.0.0
Envato WordPress Toolkit: by Envato – 1.7.2
Jetpack by WordPress.com: by Automattic – 5.9
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.5
Qode Instagram Widget: by Qode Themes – 1.2
Qode Quick Links: by Qode Themes – 1.0
Qode Twitter Feed: by Qode Themes – 1.1
Slider Revolution: by ThemePunch – 5.4.6.6
Smart Slider 3: by Nextend – 3.2.13
Strong Testimonials: by Chris Dillon – 2.30
Timetable Responsive Schedule For WordPress: by QuanticaLabs – 3.8
WD Facebook Feed: by WebDorado – 1.0.31
WooCommerce Stripe Gateway: by WooCommerce – 4.0.7
WooCommerce Services: by Automattic – 1.12.1
WooCommerce: by Automattic – 3.3.3
WP Maintenance Mode: by Designmodo – 2.1.2
WP Multilang: by Valentyn Riaboshtan – 2.2.1
WP Store Locator: by Tijmen Smit – 2.2.13
Zeno Font Resizer: by Marcel Pol – 1.7.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #228 - /shop/
Basket: #229 - /basket/
Checkout: #230 - /checkout/
My account: #231 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Bridge Child
Version: 1.0.0
Author URL: http://www.qodethemes.com/
Child Theme: ✔
Parent Theme Name: Bridge
Parent Theme Version: 13.5
Parent Theme Author URL: http://www.qodethemes.com/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: bridge/woocommerce/cart/cart-empty.php
bridge/woocommerce/cart/cart-shipping.php
bridge/woocommerce/cart/cart-totals.php
bridge/woocommerce/cart/cart.php
bridge/woocommerce/cart/shipping-calculator.php
bridge/woocommerce/checkout/form-coupon.php
bridge/woocommerce/checkout/thankyou.php
bridge/woocommerce/content-product.php
bridge-child/woocommerce/content-single-product.php
bridge/woocommerce/global/form-login.php
bridge/woocommerce/global/quantity-input.php
bridge/woocommerce/loop/add-to-cart.php
bridge/woocommerce/loop/loop-start.php
bridge/woocommerce/loop/pagination.php
bridge/woocommerce/loop/rating.php
bridge/woocommerce/loop/result-count.php
bridge/woocommerce/loop/sale-flash.php
bridge/woocommerce/myaccount/form-login.php
bridge/woocommerce/myaccount/form-lost-password.php
bridge/woocommerce/myaccount/my-address.php
bridge/woocommerce/myaccount/my-orders.php
bridge/woocommerce/single-product/add-to-cart/external.php
bridge/woocommerce/single-product/add-to-cart/grouped.php
bridge/woocommerce/single-product/add-to-cart/simple.php
bridge/woocommerce/single-product/add-to-cart/variable.php
bridge/woocommerce/single-product/related.php
bridge/woocommerce/single-product/sale-flash.php
bridge/woocommerce/single-product/tabs/additional-information.php
bridge/woocommerce/single-product/tabs/description.php
bridge/woocommerce/single-product/tabs/tabs.php
bridge/woocommerce/single-product/up-sells.php
bridge-child/woocommerce/single-product.php

`

**Comment by soft79** [comment]
It's a theme issue. See: https://themeforest.net/item/bridge-creative-multipurpose-wordpress-theme/7315054/comments?utf8=%E2%9C%93&term=apply+coupon

**Comment by Pixelatex** [comment]
I'll be... the latest update did fix it! Thanks a bunch :D
