### ISSUE TITLE
Contact Form 7 issue

### ISSUE THREAD

**Issue by dustinhan** [VaLeXaR/wp-multilang#41]
Hi, the enquiry form received from contact form 7 combine multiple language content inside the email and have the language shortcode tag [:en][:]

Any suggestions to change it to receive selected language enquiry form only and remove the shortcode tag?

**Comment by VaLeXaR** [comment]
What version of WP Multilang are You using?
Which field in the mail have the multilang tags?

**Comment by Pixelatex** [comment]
I'm getting this issue as well.. all the messages are shown in the correct language but will have [:en] and [:] around it.

**Comment by VaLeXaR** [comment]
Can anyone answer my questions so I solved the problem?

**Comment by Pixelatex** [comment]
@VaLeXaR 
I was on the 2.2.1 version and the issue appeared when a message appeared, like the success or error messages, they all showed the [:en] tags.

It was an issue with the previous version of multilang, upgrading to the latest version removed the tags and everything works perfectly now. This issue can be closed.
