### ISSUE TITLE
Shared Gutenberg blocks cannot handle individual translation

### ISSUE THREAD

**Issue by Theremingenieur** [VaLeXaR/wp-multilang#42]
Not sure if this is a WP multilang issue, but when I convert a Gutenberg Paragraph or Header block into a shared block, it's just the original language. Pasting the same shared block into a post or page with different language does not translate it, it's still shown in the original language.

I thought that Gutenberg blocks were relational sub objects of posts, but apparently they aren't... :(

**Comment by VaLeXaR** [comment]
You need to create different block. Translation Gutenberg's blocks difficult to implement. Moreover, it is still in development all the time changes.

**Comment by Theremingenieur** [comment]
Thank you for your kind reply! I had thought that blocks were independent objects in a separate SQL table with m:n relationship to posts, but apparently they are only handled inline which makes things more complicated.

Closing this and waiting for better times...
