### ISSUE TITLE
Menu links transform according to language

### ISSUE THREAD

**Issue by malchikovma** [VaLeXaR/wp-multilang#45]
Hello. I have two languages (ru/eng), and two menu accordingly (It is like one menu, but separated by your plugin).
So in backend i have following links:
* `http://localhost/?page_id=25`  for english menu 
* `http://localhost/ru/?page_id=25`  for russan menu

But in frontend i have same link for both languages. 
I have fresh wp installation 4.9.5 with only WC plugin.

Thanks.

P.S. awesome plugin btw.

**Comment by VaLeXaR** [comment]
enable permalinks in WP settings and check htaccess exist in root of your site
