### ISSUE TITLE
To many redirects for non-admin users

### ISSUE THREAD

**Issue by NielsHavermans** [VaLeXaR/wp-multilang#46]
I'm setting up some WP sites in Dutch (NL) and English (EN). Everything works just fine and as expected, except one thing: only the administrator can login to the Wordpress back-end. Other roles cannot login, the browser shows a 'wrong redirect error' (to many redirects).

I'm using the latest version of WP-Multilang, Wordpress and some other up-to-date plugins.
In my server logs there is one error: _Error dispatching request to : , referer: https://www.xxxxxxx.nl/wp-login.php?redirect_to=https%3A%2F%2Fwww.xxxxxxx.nl%2Fwp-admin%2F&reauth=1_

Is this a known issue, and how can it be solved?

**Comment by VaLeXaR** [comment]
I checked it and have no errors. Cant it be others plugins?

**Comment by NielsHavermans** [comment]
Thanks for your reply. 
I've just deactivated and activated all my plugins: problem solved! 
I thought your plugin caused the problem, it was the only plugin available on both sites and it happened after an update. Thanks again!
