### ISSUE TITLE
Menu items filter is not working

### ISSUE THREAD

**Issue by massimeddu** [VaLeXaR/wp-multilang#5]
In version 2.0.0 the menu items filter is not working anymore.

I set filters to show some custom link menu items only in one language (see screenshot) but are shown in all languages:

![screenshot from 2017-11-08 12-48-14](https://user-images.githubusercontent.com/7139196/32547703-a869f0a8-c483-11e7-91e4-0fe2b9b5c9da.png)

Thanks

**Comment by VaLeXaR** [comment]
Thank You for your report. Fixed in dev branch.

**Comment by VaLeXaR** [comment]
Fixed, pushed.
