### ISSUE TITLE
Error on translated pages

### ISSUE THREAD

**Issue by gody01** [VaLeXaR/wp-multilang#50]
On my instalation http://www.gody.si/ switching to Slovenian does not work without this patch:

diff -uNr ./wordpress/wp-content/plugins/wp-multilang/includes/class-wpm-menus.php~ ./wordpress/wp-content/plugins/wp-multilang/includes/class-wpm-menus.php
--- ./wordpress/wp-content/plugins/wp-multilang/includes/class-wpm-menus.php~	2018-04-27 08:41:09.000000000 +0200
+++ ./wordpress/wp-content/plugins/wp-multilang/includes/class-wpm-menus.php	2018-04-27 08:42:11.955320769 +0200
@@ -37,7 +37,7 @@
 	 * @return mixed
 	 */
 	public function filter_menus( $items ) {
-		foreach ( (array) $items as &$item ) {
+		foreach ( (array) $items as $item ) {
 			$item['title'] = wpm_translate_string( $item['title'] );
 		}

**Comment by VaLeXaR** [comment]
Use PHP 5.6 and greater.

**Comment by gody01** [comment]
Thanks for the info.
