### ISSUE TITLE
Changing the slug on a translated page made every translated page a copy of 'home'

### ISSUE THREAD

**Issue by Pixelatex** [VaLeXaR/wp-multilang#51]
I changed the slug on a translated page, just to try something. And now everything except the default language is a copy of home, I'm looking for a way to clear the translated pages back to the original but not having any luck so far... :/

**Comment by VaLeXaR** [comment]
It is very strange. I need more info about it.

**Comment by Pixelatex** [comment]
@VaLeXaR I reinstalled the plugin and let it delete all its data.

Now it's fine... I'll close this as it might be a really exotic bug
