### ISSUE TITLE
Browser redirect doesn't work if the default language is English

### ISSUE THREAD

**Issue by danielgomon** [VaLeXaR/wp-multilang#52]
The browser redirection doesn't work if the default language is English.

I'm trying to setup a website with english as the default language and spanish as the second language, but the redirection only works on Chrome, not in Edge or Firefox.

We set spanish as the default language, as a workararound, but we have more english spoken users, so this add an unecessary redirect to that users.

**Comment by VaLeXaR** [comment]
Can You give me a site link?

**Comment by Thedemon007** [comment]
i have same problem holidaysrental. eu

**Comment by VaLeXaR** [comment]
The redirect works only once. Then uses cookie for checking user language.

**Comment by VaLeXaR** [comment]
Check Your browser language. The plugin check a language of browser and make redirect to browser language in first time.

**Comment by Thedemon007** [comment]
Ok yeah is working now i tested it in firefox only change once about:config  -> intl.accept_languages chage volue for es-ES, es or en-US, en ... test in new private window each value
