### ISSUE TITLE
Language mess up with same post in multiple tabs

### ISSUE THREAD

**Issue by BernhardWebstudio** [VaLeXaR/wp-multilang#61]
Thank you for this awesome plugin! 
I unfortunately do have a minor issue to report (maybe I am doing something wrong). 
Example situation: blog with this plugin installed, languages German & English. The editor of a post (yet only existing in German) is opened for English. In a new tab, the German version of the post gets opened, e.g. for copy-pasting via Google Translate into the English tab. When saving the English version, the German gets updated to use the English text, the English stays empty. This does not happen if the German version is opened first. 

TLDUnderstand: post gets saved to the wrong language when opening that language in a new tab before saving but after opening

Version using: 2.2.5, WP: 4.9.6–en_GB

**Comment by VaLeXaR** [comment]
Hi. This behavior described in FAQ to the plugin.
