### ISSUE TITLE
Redirect first time

### ISSUE THREAD

**Issue by alexey13** [VaLeXaR/wp-multilang#63]
Good day! First of all - plugin is awesome, thank you. I have 2 languages English and Russian. The first time it recognized the language of my browser and redirect me to ru version (as I set in options to redirect the first time), but after it does not show me ru version. What is the proper behavior? Should it check cookie and show ru version? Or ru version should work even without ru in end of a slug when plugin read cookie?

**Comment by alexey13** [comment]
Resolved added to class-wpm-setup.php after line 624
//add redirection 
$browser_language = $this->get_browser_language();

if ( $browser_language && ( $browser_language !== $user_language ) ) {
	wp_redirect( wpm_translate_current_url( $browser_language ) );
	exit;
}
//end add

**Comment by VaLeXaR** [comment]
Use action 'wpm_changed_language' for set up needed function.
