### ISSUE TITLE
WP Custom links as menu items with translation possible?

### ISSUE THREAD

**Issue by Theremingenieur** [VaLeXaR/wp-multilang#65]
Actually, when creating a custom link in the WP main menu, for example /mypage/#myanchor, and when I'm calling it being on the French or German translation of the page, i.e. /de/mypage/ or /fr/mypage, clicking that custom link would always open the English version of the page before jumping to the anchor. How can I get these custom link urls rewritten, so that /de or /fr would be added automatically, depending on the calling context?

**Comment by VaLeXaR** [comment]
Hi. You have to add custom link with domen. Like http://custom.com/mypage/#myanchor

**Comment by Theremingenieur** [comment]
Yes, that works! Thank you very much! Merci beaucoup! Велике спасибі!

**Comment by sufiyanshahid592** [comment]
i have use custom link with domain but still not working
