### ISSUE TITLE
How to use wp-multilang with Carbon Fields?

### ISSUE THREAD

**Issue by steffenster** [VaLeXaR/wp-multilang#66]
Hi,
I use CarbonFields https://carbonfields.net/ to create custom fields. Is there a way to use this library with wp-multilang?
Thx a lot!

**Comment by VaLeXaR** [comment]
You can set configuration for each needed field.

**Comment by steffenster** [comment]
This is not working. CarbonFields is building fields with React. Maybe this is the challenge.
