### ISSUE TITLE
Widget with problems.

### ISSUE THREAD

**Issue by alexmorenogc** [VaLeXaR/wp-multilang#67]
Hello VaLeXaR,

There are some problem with language switcher, because there are many post in wordpress support:
https://wordpress.org/support/plugin/wp-multilang

This one is mine:
https://wordpress.org/support/topic/widget-in-mobile-not-working/

Thank you very much.
Alex Moreno

**Comment by VaLeXaR** [comment]
Hi. I answer on WP forum.
