### ISSUE TITLE
Parse error: syntax error, unexpected '&' in .../wp-content/plugins/wp-multilang/includes/class-wpm-menus.php on line 40

### ISSUE THREAD

**Issue by fremsoft** [VaLeXaR/wp-multilang#68]
In wp-multilang Plugin version: 2.2.5 at line 40 removing '& ' it works!

(before)
... 
foreach ( (array) $items as &$item ) {
...

(after)
... 
foreach ( (array) $items as $item ) {
...

**Comment by soft79** [comment]
That has side effects. Either update to PHP 5.6 or newer or do this:

```
foreach ( (array) $items as $key => $item ) {
			$items[$key]['title'] = wpm_translate_string( $item['title'] );
		}
```

**Comment by fremsoft** [comment]
It is already running on PHP 5.6+

**Comment by soft79** [comment]
Oh yes, I see. It's because of the casting to array.  You're right, ampersand can go.
