### ISSUE TITLE
Language selector disappeared again in Gutenberg 3.8.0

### ISSUE THREAD

**Issue by Theremingenieur** [VaLeXaR/wp-multilang#72]
Title says it all. In the single post or single page editors, the language selector disappeared from the top left corner...

**Comment by Theremingenieur** [comment]
Still broken in Gutenberg 3.9.0...

**Comment by Theremingenieur** [comment]
I wonder if this plugin is still under active development...

**Comment by Theremingenieur** [comment]
Hoping for a WP5 compatible update today...

**Comment by Theremingenieur** [comment]
Even without WP5, switching to a different theme and back fixed it...?!?

**Comment by chiyi4488** [comment]
![image](https://user-images.githubusercontent.com/30853081/49786831-fd686d80-fd5f-11e8-8123-e7262ab1b03f.png)
??

**Comment by soft79** [comment]
The update is out. Does it work for you now?

**Comment by chiyi4488** [comment]
I haven't found any problems with the use, I just don't understand the problem that @Theremingenieur said.

**Comment by soft79** [comment]
Previous version didn't work with Gutenberg anymore. Yesterday VaLeXaR released a fix. Therefore I asked @Theremingenieur if it works now.

**Comment by Theremingenieur** [comment]
Everything seems to work so far for me. Thank you!

**Comment by chiyi4488** [comment]
@soft79 I want to be the main translator for your project (Traditional Chinese, Taiwan)
Wait a moment, I will try to translate all of them, please help review :)
maybe 1 hours

**Comment by chiyi4488** [comment]
finish
