### ISSUE TITLE
Cannot translate menu items in SPA

### ISSUE THREAD

**Issue by FallenAngel97** [VaLeXaR/wp-multilang#86]
Hello, thanks for your plugin. 
I have an issue with it. Here's the code: 

```
function f97a_getMenu(WP_REST_Request $request) {
    $param = $request['langTag'];
    $menu_name = 'header-menu';
    $locations = get_nav_menu_locations();
    $menu = wp_get_nav_menu_items($locations[$menu_name]);
    return wpm_translate_value($menu, 'ru');
}
```

But wpm_translate_value does not translate the items, they're left unchanged. I have checked, if `function_exists` and it returned `true`. But I noticed in your source code https://github.com/VaLeXaR/wp-multilang/blob/f56b620586a9b53cde0cec8d8815b87ed211db48/includes/class-wpm-menus.php#L55 This one. Maybe I can use this one? Because the only thing, that comes to my mind is fetch manually from database string and split it. Can you help, please? Also, permalinks are enabled: 
![default](https://user-images.githubusercontent.com/14362650/49793911-f2e9ac00-fd3e-11e8-901a-bb31a10d3fcb.png)

**Comment by soft79** [comment]
What do you get if you `error_log( print_r( $menu, true ) )` after wp_get_nav_menu_items?

**Comment by FallenAngel97** [comment]
> 
> 
> What do you get if you `error_log( print_r( $menu, true ) )` after wp_get_nav_menu_items?

Thanks for reply. Here it is:
![default](https://user-images.githubusercontent.com/14362650/49806089-76b39080-fd5f-11e8-90c7-cba20c30ce60.png)

**Comment by soft79** [comment]
It looks like the result of wp_get_nav_menu_items has already been translated to English by WPM. Maybe this works:

YOUR-DOMAIN/ru/wp-json/f97a/getMenu 

You need to find a way to set the right language before calling f97a_getMenu.

**Comment by FallenAngel97** [comment]
How to close this issue?
