### ISSUE TITLE
Can I translate custom taxonomy and custom post type?

### ISSUE THREAD

**Issue by yaquawa** [VaLeXaR/wp-multilang#89]
How can I translate custom taxonomy and custom post type !?

**Comment by rubenmeines** [comment]
Hi,

if you add a file named wpm-config.json to your theme root. With this code:
`{
	"post_types": {
		"post_type_name": {}
	},
	"taxonomies": {
		"taxonomy_name": {}
	}
}`

and you change "post_type_name" for the name of your post type and "taxonomy_name" for the name of your taxonomy it should work. You should see the language switcher when you go to the post type.
