### ISSUE TITLE
SiteOrigin Panels

### ISSUE THREAD

**Issue by soft79** [VaLeXaR/wp-multilang#9]
Hi, I'm having two issues with the SiteOrigin panels...

**1.** If a widget is not a site origin widget it does not have a '_sow_form_id'. Replacing line 45 in class-wpm-pbso.php seems to fix the issue:

`if ( $widget['_sow_form_id'] === $_widget['_sow_form_id'] )`
replace by:
`if ( $widget['panels_info']['widget_id'] === $_widget['panels_info']['widget_id'] )`

---- 
**2.** For some reason when I update a widget in one language; the other language(s) are emptied. This seem to occur because the filter `wpm_filter_old_panels_data_meta_value` is not called.

If I comment the following if statement in `abstract-wpm-object.php:188` the problem seems to be solved, but I'm afraid this might break things. Maybe you have an idea what is going on? And how to fix it?

```
//Commenting this if {} fixes the issue, but why? And does it have side-effects?
//if ( ! wpm_is_ml_value( $meta_value ) ) {
	$old_value  = $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->{$this->object_table}} WHERE meta_key = %s AND {$column} = %d LIMIT 1;", $meta_key, $object_id ) );
	$old_value  = maybe_unserialize( $old_value );
	$old_value  = apply_filters( "wpm_filter_old_{$meta_key}_meta_value", $old_value, $meta_value );
	$meta_value = wpm_set_new_value( $old_value, $meta_value, $meta_config );
//}
```

**Comment by VaLeXaR** [comment]
Hi @soft79 
1. ['panels_info']['widget_id'] not equal ['_sow_form_id']. This is different values. I changed _sow_form_id to widget_id. Thanks for your remark.
2. If data not changed, SiteOrigin panels do not save meta fields.

**Comment by VaLeXaR** [comment]
Fixed
