### ISSUE TITLE
Turning off wp-multilang leave country prefix

### ISSUE THREAD

**Issue by Madefoka** [VaLeXaR/wp-multilang#99]
I want to turn off the plugin but after doing that I have before every sentence country prefix of site language. How to get rid of that?. Is such an annoyance. You want to turn off but it's not possible. 
![WP Multilang error](https://user-images.githubusercontent.com/17600141/55414396-4d677c00-556b-11e9-8aaf-37bdc545bd95.jpg)

**Comment by soft79** [comment]
Edit your message and remove foul language if you want help.

**Comment by viktorbrain** [comment]
I have the same issue. And at any post/project/site which I edit :( please help!

**Comment by soft79** [comment]
First take a backup of your database, just in case.

On the settings page of WP-Miltilang check 'Delete translations when uninstalling plugin'. Then deactivate and uninstall the plugin.

**Comment by Madefoka** [comment]
Nothing. It doesn't work. I still have the -  [:pl]  - before every sentence.

**Comment by soft79** [comment]
Please describe the steps you took to in more detail (step-by-step). Maybe you missed a step. 

Did you get any error messages? What plugins do you have installed and what theme do you use?

**Comment by Madefoka** [comment]
Well, there is no much steps. 1. Checking: Delete translations when uninstalling plugin (some translations may not be deleted and you must delete them manually). - saved. 2. Then on the plugin page i'm deactived the plugin and i check the site. And there before every sentence is the country prefix - [:pl]. So I actived the plugin back. Prefix is gone.

**Comment by soft79** [comment]
Try the step 'uninstall' after 'deactivate'.

**Comment by Madefoka** [comment]
yes and then i have no steps to turning site to normal view. Great idea. Thanks.

**Comment by soft79** [comment]
Ofcourse you can. Either reinstall the plugin or restore the backup.

**Comment by Madefoka** [comment]
ok you mother........ :) it's working :) Thanks a lot :)

**Comment by soft79** [comment]
Try to communicate friendlier in the future...
